"""change quote final_amount to numeric 20 2

Revision ID: 061ddeb2c5b6
Revises: 275088ab6e86
Create Date: 2026-05-07 17:05:08.440297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061ddeb2c5b6'
down_revision: Union[str, None] = '275088ab6e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes', 'final_amount',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes', 'final_amount',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=20, scale=6),
               existing_nullable=False)
    # ### end Alembic commands ###
