"""increase quote rate precision to numeric 20 10

Revision ID: 5df28da6200c
Revises: 061ddeb2c5b6
Create Date: 2026-05-07 17:08:03.494568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df28da6200c'
down_revision: Union[str, None] = '061ddeb2c5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes', 'rate',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes', 'rate',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.NUMERIC(precision=20, scale=6),
               existing_nullable=False)
    # ### end Alembic commands ###
